### ISSUE TITLE
Does not work when using Yarn Plug'n'play.

### ISSUE THREAD

**Issue by Ulyanov-programmer** [thewebartisan7/posthtml-components#33]
_Greetings!_

I tried to run your plugin through the **`yarn`** package manager, using **`plug'n'play`** technology. 
I was running the plugin via `gulp`.
<details><summary>Launch code</summary>

```javascript
import gulp from 'gulp'
import browsersync from 'browser-sync'
import posthtml from 'gulp-posthtml'
import component from 'posthtml-component'

export default function html() {
  return gulp.src(paths.scr.html)
    .pipe(posthtml([
      component({
        root: './src',
        folders: ['components'],
      }),
    ], {}))

   // another code

    .pipe(gulp.dest(paths.build.html))
    .pipe(browsersync.stream())
}
``` 
</details> 

When importing (it is when importing, the code in the task does not affect) yarn throws the following error:

<details><summary>Error in terminal:</summary>

```shell
Error: posthtml-component tried to access posthtml, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: posthtml (via "posthtml\lib\api")
Required by: posthtml-component@npm:1.1.0 (via C:\Users\ccold\Desktop\gulp_multitool\.yarn\cache\posthtml-component-npm-1.1.0-25202f75ea-e80a90023f.zip\node_modules\posthtml-component\src\)

Require stack:
- C:\Users\ccold\Desktop\gulp_multitool\.yarn\cache\posthtml-component-npm-1.1.0-25202f75ea-e80a90023f.zip\node_modules\posthtml-component\src\index.js
    at require$$0.Module._resolveFilename (C:\Users\ccold\Desktop\gulp_multitool\.pnp.cjs:19041:13)
    at require$$0.Module._load (C:\Users\ccold\Desktop\gulp_multitool\.pnp.cjs:18891:42)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\ccold\Desktop\gulp_multitool\.yarn\cache\posthtml-component-npm-1.1.0-25202f75ea-e80a90023f.zip\node_modules\posthtml-component\src\index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at require$$0.Module._extensions..js (C:\Users\ccold\Desktop\gulp_multitool\.pnp.cjs:19085:33)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at require$$0.Module._load (C:\Users\ccold\Desktop\gulp_multitool\.pnp.cjs:18904:22)
``` 

</details> 

_This is similar to a typical error for plugins not adapted for yarn plug'n'play, which consists in an ambiguous designation of a dependency on another package._ 

A [link on the repository](https://github.com/Ulyanov-programmer/gulp_multitool/tree/develop) (see the **_develop_** branch) where I conducted the launch.

These links should help you: 
[Documentation of Yarn plug'n'play technology](https://yarnpkg.com/features/pnp)
[API documentation for this technology](https://yarnpkg.com/advanced/pnpapi)
[A page on stackoverflow, which, apparently, refers to this problem](https://stackoverflow.com/questions/62298396/making-a-dependencys-dependencies-available-with-yarn-2)

P.S: _I managed to find a temporary solution, it consists in explicitly specifying dependencies. After entering the code, you must use the `yarn` command._

<details><summary>Code in .yarnrc.yml</summary>

```yml
packageExtensions:
  posthtml-component@*:
   dependencies:
      posthtml: '*'
  posthtml-expressions@*:
    dependencies:
      posthtml: '*'
``` 
</details>

**Comment by Ulyanov-programmer** [comment]
At the moment, a temporary solution is enough _for me personally_. 
This issue can be postponed for a very long time, anyway, yarn plug'n'play is the lot of a few...

And although the installation _via yarn install works stably_, in the future, it is desirable to find a solution, because it is not very convenient for each user to describe dependencies separately if they want to use plug'n'play.

**Comment by thewebartisan7** [comment]
I will surely look into. stackoverflow solution seem cover all package manager, but not sure pro and cons.
I will also check how others posthtml plugin handle this, if they even handle it. By quickly checking a few it seem doesn't.

**Comment by Ulyanov-programmer** [comment]
Some packages work stably (such as [posthtml-easy-bem](https://github.com/semencov/posthtml-easy-bem) and [posthtml-img-autosize](https://github.com/posthtml/posthtml-img-autosize)), but there are also those that do not work (like [posthtml-beautify](https://github.com/posthtml/posthtml-beautify)).

**Comment by thewebartisan7** [comment]
> Some packages work stably (such as [posthtml-easy-bem](https://github.com/semencov/posthtml-easy-bem) and [posthtml-img-autosize](https://github.com/posthtml/posthtml-img-autosize))

Can't find how they solve yarn issue?

**Comment by Ulyanov-programmer** [comment]
_You are a cunning man, however!_
I rummaged through the repository files of some plugins. 
As far as I remember, plug'n'play doesn't like it when a module references something that isn't in package.json. 

In the executable files of plugins that did not work, there is a similar import:
```js
... require('posthtml/lib/api');
```

Yarn does not understand where you are referring to, therefore it gives an error.
There were no similar imports in the files of other plugins (one of them had no imports at all).
Otherwise, I'm just guessing.

**Comment by Ulyanov-programmer** [comment]
I'll do a PR where I'll try to change the import style.

**Comment by thewebartisan7** [comment]
> I will try to make changes in my local copy of the plugin.

Have you checked if this works?

**Comment by Ulyanov-programmer** [comment]
There are times when it's better for me not to do anything for my own health. Wait for some time, I will recover my strength and I will go back to work.

**Comment by thewebartisan7** [comment]
There is no hurry! Health first. If I find time I will try to reproduce the problem, and solve it. If you already have a repo with gulp + yarn send me the link, otherwise I try to recreate it. I haven't used gulp for long time.

**Comment by thewebartisan7** [comment]
@Ulyanov-programmer  

>  By the way, judging by these lines, yarn sees all dependencies (if I didn't miss anything), except posthtml, even Lodash.

I think I figured out the problem because of this. posthtml was under `devDependencies` instead of under  `dependencies`. 

This commit should fixes the issue:

https://github.com/thewebartisan7/posthtml-components/commit/0c79060ffd770883a7529d6d4b7960eadd834bec#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Basically I just move `posthtml` from `devDependencies` to `dependencies`.
It seem like yarn plug'n'play works isolated for each packages, while in standard npm, even if a package is for example added in your project or in some other package, it still being found.

I did test with your repo and works fine.

Just add in your package.json this:

"posthtml-component": "github:thewebartisan7/posthtml-components#main",

to use latest version.

This is the output after updating:

<img width="1621" alt="Screenshot 2023-05-17 at 12 40 18" src="https://github.com/thewebartisan7/posthtml-components/assets/57477934/8bfcdac4-9b04-44ce-b12d-0a639db2ca3d">

Please to confirm that also works for you everything else, and then I will release new `1.1.1` version.

Thanks!

**Comment by Ulyanov-programmer** [comment]
If you think it's none of your business and/or you can't fix it, write here and close the issue.

**Comment by thewebartisan7** [comment]
Try open an issue on posthtml-expression, I am sure @Scrum will be happy to fix this issue.

To me seem the same issues, since I can see in console:

```
➤ YN0002: │ posthtml-expressions@npm:1.11.0 doesn't provide posthtml (p3eafc), requested by posthtml-match-helper
```

So basically just update package.json:

https://github.com/posthtml/posthtml-expressions/blob/master/package.json#L25

If @Scum confirm you may just try to open a PR.

I don't think I can solve this without updating directly posthtml-expression plugin.

However, I notice there is same issue with `prettier-plugin-css-order`, see screenshot attached:

<img width="1034" alt="Screenshot 2023-05-17 at 13 39 44" src="https://github.com/thewebartisan7/posthtml-components/assets/57477934/c7915c7f-af45-4822-ae41-5c06914157bd">

If there is anything I can fix in this plugin, let me know.

**Comment by Ulyanov-programmer** [comment]
The issue with the dependency of plugin posthtml-expressions has been resolved, try to update your plugin.
https://github.com/posthtml/posthtml-expressions/issues/151
https://github.com/posthtml/posthtml-expressions/releases/tag/v1.11.1
